language: ruby
rvm:
- 2.6.6
sudo: false
deploy:
  provider: heroku
  run: rake db:migrate
  api_key:
    secure: PmXa1bDRu4qnT6Rf3kMm5Xt3l4jZBG9Y9B3nr/YEk3cwGrYW8rV79g44dS4m0yuKPbgxSx8bTkaomtfcYDmgBO7Xefa8a6qyQS2EmyPCRHuX7kXGURD06gPyhluauf+5fwoTRZ89FJ5o6rjg43fQ5NSC+VjuxMtrK4SJPTGdWAA=
