language: ruby
rvm:
- 2.4.1
sudo: false
deploy:
  provider: heroku
  run: "rake db:migrate"
  api_key:
    secure: M9/2u9+ZHcLWW43CsnxFeWmaIiwsba1dH4v+5WAqscZmuhAx5ijRRvkB0LV7TvsduFKv2nybqkk6nIl7uFIcdG2KwwTk7w0lRsm/buXJ2+9uzbcCY3q2DkTwzneao0E4AGVTQA+YEMSbG3s2iDXLuIMIVryuKdEaHcb9PMTMKoE=
